### ISSUE TITLE
How to link function parameters to e.g.  p0=[5, -1, 1]

### ISSUE THREAD

**Issue by rus-ace** [venkatesannaveen/python-science-tutorial#4]
Awful that for the Gaussian fit you do not show correspondence between p0 and a, b, c,. Which is which?
That is, how does one define and or link here and in general the function parameters such as your a,b,c to e.g. p0=[5, -1, 1].

**Comment by naveenv92** [comment]
The values in `p0` are in order of where they appear in the function, in this case in the function definition of the Gaussian, we have:

```python
def gaussian(x, a, b, c)
```

- `x` is the independent variable so it appears first in the function definition and is supplied by the `xdata` argument in `scipy.curve_fit`
- The remaining inputs are the parameters that will be manipulated by `scipy.curve_fit` in order to fit `xdata` to `ydata`, so in this case `p0[0] = a, p0[1] = b, p0[2] = c`
